### ISSUE TITLE
[Forge - 1.19.2]: Debug line for infestation enchant

### ISSUE THREAD

**Issue by SiverDX** [electrickiwi23/modular-enchantments#2]
**Version**: 1.4.3

Should be removed:

![image](https://github.com/electrickiwi23/modular-enchantments/assets/22003703/36376ec0-12ec-47a9-9bff-f4eee6f96bc9)

**Comment by electrickiwi23** [comment]
Thanks for the heads up, removed that along with a few other debug lines along with fixing that bug with the mining speed.
